# Site settings
title: frobnitzem.github.io
url: https://frobnitzem.github.io
email: predictivestatmech@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Massively Parallel Computational Mathematical Maniacal
  Theoretical GeoBioPhysicalIconoclasticEconoChemist.
github_username: frobnitzem

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "David M. Rogers"
      comments: true

# Gems settings
plugins:
 - jekyll-paginate
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-mentions

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate: 5

sass:
    style: compressed
